default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library-app_development

test:
  <<: *default
  database: library-app_test

production:
  <<: *default
  database: library-app_production
  username: library-app
  password: <%= ENV['LIBRARY-APP_DATABASE_PASSWORD'] %>
